[program:jupyter]
command=/bin/bash -lc "source /venv/main/bin/activate && python3 -m jupyterlab --ip=0.0.0.0 --port=8889 --no-browser --allow-root --ServerApp.token='' --ServerApp.password='' --ServerApp.allow_origin='*' --ServerApp.disable_check_xsrf=True"
directory=/workspace
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/workspace/jupyter.log
stderr_logfile=/workspace/jupyter.err.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
